site_name: Building Attention
site_url: http://github.com/fuas-ixd/pulse
site_description: IXD
site_author: IXD Fontys ICT
repo_url: https://github.com/fuas-ixd-pulse/magazine
edit_uri_template: 'blob/main/docs/{path}'
copyright: © 2024. Licensed via CC BY-NC-SA 4.0
remote_branch: gh-pages
use_directory_urls: false
theme:
  name: material
  palette:
    primary: deep purple
  features:
    - toc.follow
    - toc.integrate
    - announce.dismiss
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    #- navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.instant.preview
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    # - navigation.path
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - tables
  - toc:
      permalink: "#"
# Following items break the build
# - md_in_html
#  - pymdownx.emoji:
#      emoji_index: !!python/name:material.extensions.emoji.twemoji
#      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: vega-lite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: false
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.critic
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5 
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
  - javascripts/mathjax.js
  - javascripts/mermaid.js
plugins:
  - with-pdf:
      debug_html: true
      output_path: book.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
      cover: true
      back_cover: true
      cover_title: Digital Communities
      cover_subtitle: IXD Fontys ICT
      cover_logo: fontys-white.svg
      toc_title: Contents
      #excludes_children:
      #  - 'blog/'
      #exclude_pages:
      #  - 'blog/'
      #  - 'tags/'
      render_js: true
      use_relaxed_js_renderer: true
      headless_chrome_path: chrome
  #- pdf-export:
  #    enabled_if_env: ENABLE_PDF_EXPORT
  - charts
  - search
  #- tags:
  #    tags_file: tags.md
  - callouts
  - glightbox
  - mkdocs-jupyter
  - roamlinks
  - blog:
      authors: true
      date_from_meta:
        as_creation: date
  #- rss:
  #    categories:
  #      - categories
  #      - tags
  - git-revision-date-localized:
      fallback_to_build_date: true
  - git-committers:
      repository: fuas-ixd-pulse/magazine
      branch: main
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fuas-ixd-pulse/magazine
nav: